esp8266:
  board: nodemcuv2
  framework:
    version: recommended


uart:
  id: uart_bus
  rx_pin: D5
  baud_rate: 9600
  data_bits: 8
  parity: NONE
  stop_bits: 1

sml:
  id: mysml
  uart_id: uart_bus

sensor:
  - platform: sml
    name: "Total energy"
    sml_id: mysml
    #server_id: "0123456789abcdef"
    obis_code: "1-0:1.8.0"
    unit_of_measurement: kWh
    accuracy_decimals: 1
    device_class: energy
    state_class: total_increasing
    filters:
      - multiply: 0.0001

text_sensor:
  - platform: sml
    name: "Manufacturer"
    sml_id: mysml
    #server_id: "0123456789abcdef"
    obis_code: "129-129:199.130.3"
    format: text
