light:
  - platform: binary
    name: "${friendly_name}"
    output: shelly_relay
    id: lightid

output:
  - platform: gpio
    pin: GPIO4
    id: shelly_relay

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO5
    name: "${friendly_name} input"
    on_state:
      then:
        - light.toggle: lightid
    on_multi_click:
      - timing:
          - ON for at most 0.5s
          - OFF for at most 0.5s
          - ON for at most 0.5s
          - OFF for at most 0.5s
          - ON for at most 0.5s
          - OFF for at most 0.5s
        then:
          - button.press: btn_restart
