binary_sensor:
  - platform: gpio
    id: input_1
    pin:
      number: GPIO13
    name: "${channel_1} input"
    on_multi_click:
      - timing:
          - ON for at most 0.5s
          - OFF for at most 0.5s
          - ON for at most 0.5s
          - OFF for at most 0.5s
          - ON for at most 0.5s
          - OFF for at most 0.5s
        then:
          - button.press: btn_restart
