light:
  - platform: binary
    name: "${channel_2}"
    output: shelly_25_relay_2
    id: lightid2

output:
  - platform: gpio
    pin: GPIO15
    id: shelly_25_relay_2

binary_sensor:
  - platform: gpio
    id: input_2
    pin:
      number: GPIO5
    name: "${channel_2} input"
    on_state:
      then:
         - light.toggle: lightid2
    on_multi_click:
      - timing:
          - ON for at most 0.5s
          - OFF for at most 0.5s
          - ON for at most 0.5s
          - OFF for at most 0.5s
          - ON for at most 0.5s
          - OFF for at most 0.5s
        then:
          - button.press: btn_restart
