# Main Device for Shelly 2.5
# Including temperature monitoring and auto switch-off at high temperature
#
# Needed Subtitutions
# friendly_name -> Name of the Device
# max_temp -> Maximum device temperature in °C (example 75)
#
# Neccesary Script:
# The Script "all_off" is neccesary. This is called at hight temperature

esphome:
  platform: ESP8266
  board: esp01_1m
#time:
#  - platform: sntp
#    id: my_time

i2c:
  sda: GPIO12
  scl: GPIO14

sensor:

  # NTC Temperature
  - platform: ntc
    sensor: temp_resistance_reading
    name: ${friendly_name} temperature
    entity_category: diagnostic
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    icon: "mdi:thermometer"
    calibration:
      b_constant: 3350
      reference_resistance: 10kOhm
      reference_temperature: 298.15K
    on_value_range:
      - above: ${max_temp}
        then:
          - script.execute: all_off
          - homeassistant.service:
              service: persistent_notification.create
              data:
                title: Message from ${friendly_name}
              data_template:
                message: Switch turned off because temperature exceeded ${max_temp}°C
  - platform: resistance
    id: temp_resistance_reading
    sensor: temp_analog_reading
    configuration: DOWNSTREAM
    resistor: 32kOhm
  - platform: adc
    id: temp_analog_reading
    pin: A0

status_led:
  pin:
    number: GPIO0
    inverted: yes
