# Binary sensor for the power button
binary_sensor:
  - platform: gpio
    name: ${friendly_name} Power Button
    id: button1
    pin:
      number: GPIO3
      inverted: true
    on_press:
      - switch.toggle: power_switch

switch:
  # Switch to restart the plug
  - platform: gpio
    id: power_switch
    pin: GPIO14
    name: ${friendly_name} Power Switch
    restore_mode: RESTORE_DEFAULT_OFF

